from gi.repository import Gio, Gtk

def export_clipboard(string: str) -> None: ...
def export_file(string: str) -> None: ...
def on_export_file(file_dialog: Gtk.FileDialog, result: Gio.Task, string: str): ...