from gi.repository import Gio, Gtk  # type: ignore

def select_dir(*_args) -> None: ...
def on_selected_dir(file_dialog: Gtk.FileDialog, result: Gio.Task) -> None: ...
def select_lyrics_file(*_args) -> None: ...
def on_selected_lyrics_file(file_dialog: Gtk.FileDialog, result: Gio.Task) -> None: ...
